backend:
  name: github
  repo: MDevEditor/aura-noir-site
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: products
    label: Products
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }
