backend:
  name: github
  repo: MDevEditor/aura-noir-site
  branch: main
  base_url: https://aura-noir-cms-auth.mohammadi-7162.workers.dev
  auth_endpoint: /.netlify/functions/auth

site_url: https://aura-noir-site-git.pages.dev

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
