backend:
  name: github
  repo: Mohammadi-7162/aura-noir-site
  branch: main
  base_url: "https://aura-noir-auth.mohammadi-7162.workers.dev"

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "public/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
